createResult:
  handler: src/api/handlers/results/createResult/createResultHandler.createResult
  package:
    patterns:
      - src/api/handlers/results/createResult/**
  events:
    - http: # Se indica que el evento se disparará mediante una solicitud http
        path: /results
        method: post
createRandomResult:
  handler: src/api/handlers/results/createRandomResult/createRandomResultHandler.createRandomResult
  package:
    patterns:
      - src/api/handlers/results/createRandomResult/**
  events:
    - http: # Se indica que el evento se disparará mediante una solicitud http
        path: /results/randomResults
        method: post
updateResult:
  handler: src/api/handlers/results/updateResult/updateResultHandler.updateResult
  package:
    patterns:
      - src/api/handlers/results/updateResult/**
  events:
    - http:
        path: /results/{id}
        method: put
deleteResult:
  handler: src/api/handlers/results/deleteResult/deleteResultHandler.deleteResult
  package:
    patterns:
      - src/api/handlers/results/deleteResult/**
  events:
    - http:
        path: /results/{id}
        method: delete

# getResult:
#   handler: src/api/handlers/results/getResult/getResultHandler.getResult
#   package:
#     patterns:
#       - src/api/handlers/results/getResult/**
#   events:
#     - http:
#         path: /results/{id}
#         method: get
# addRandomResult:
#   handler: src/api/handlers/results/resultHandler.addRandomResult
#   package:
#     patterns:
#       - src/api/handlers/results/**
#   events:
#     - http:
#         path: /result/randomResult
#         method: post